version: '3.8'

services:
  app:
    build: .
    container_name: my-go-app
    restart: unless-stopped
    ports:
      - "8080:8080"  # Пробрасываем порт приложения
    volumes:
      - ./config.json:/app/config.json  # Монтируем конфиг 
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
