name: Testing

# Запуск при пуше в любую ветку.
on:
  push:
    branches:
      - '**'

jobs:

  tests:
    runs-on: ubuntu-latest
    
    steps:
      # Установка Go версии 1.22.
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.22

      # Получение исходного кода из репозитория.  
      - name: Check out code
        uses: actions/checkout@v3

      # Запуск юнит-тестов.
      - name: Unit tests
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          go test -race -count 100 ./...